In [1]:
import pandas as pd

```bash
pip install sqlalchemy psycopg2-binary 
```

In [2]:
from sqlalchemy import create_engine

In [3]:
engine = create_engine("postgresql://root:root@localhost:5432/ny_taxi")

In [4]:
engine.connect()

In [5]:
query = """
SELECT 1 as number;
"""

pd.read_sql(query, con=engine)

   number
0       1

In [12]:
query = """
SELECT *
FROM pg_catalog.pg_tables
WHERE schemaname != 'pg_catalog' AND 
    schemaname != 'information_schema';
"""

pd.read_sql(query, con=engine)

,schemaname,tablename,tableowner,tablespace,hasindexes,hasrules,hastriggers,rowsecurity
0,public,ny_taxi_data,root,None,True,False,False,False
1,public,yellow_tripdata_trip,root,None,False,False,False,False

In [8]:
df = pd.read_parquet('yellow_tripdata_2021-01.parquet')

In [9]:
df.tpep_pickup_datetime = pd.to_datetime(df.tpep_pickup_datetime)
df.tpep_dropoff_datetime = pd.to_datetime(df.tpep_dropoff_datetime)

In [10]:
df.to_sql(name='yellow_tripdata_trip', con=engine, index=False)

KeyboardInterrupt:

In [11]:
query = """
SELECT * FROM yellow_tripdata_trip LIMIT 10
"""

pd.read_sql(query, con=engine)

Empty DataFrame
Columns: [VendorID, tpep_pickup_datetime, tpep_dropoff_datetime, passenger_count, trip_distance, RatecodeID, store_and_fwd_flag, PULocationID, DOLocationID, payment_type, fare_amount, extra, mta_tax, tip_amount, tolls_amount, improvement_surcharge, total_amount, congestion_surcharge, airport_fee]
Index: []

```sql
SELECT *
FROM pg_catalog.pg_tables
WHERE schemaname != 'pg_catalog' AND 
    schemaname != 'information_schema';
```

Source: https://www.postgresqltutorial.com/postgresql-show-tables/